#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

[ "$USER" = "root" ] # USER MUST BE root

mkidr -p "$logdir"
chonw www-data:www-data "$logdir"

### INSTALLL THIS SYSTEM ###
rsync -av --delete "$(dirname $0)/bin/" "$appdir/"
chown www-data:www-data "$appdir" -R

### RENAME FETCH CGI ###
cd "$appdir"
rnd=$(cat /dev/urandom | tr -cd 0-9a-zA-Z | head -c 32)
[ -e "/home/diverge/rnd" ] && rnd=$(cat /home/diverge/rnd ) #REMOVE OM RELEASE!!!
mv "fetch" "fetch_$rnd.cgi"

### PULL AIRICLE REPO ###
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R

echo "call fetch_$rnd.cgi from Github"